# Generated by Django 2.0 on 2018-01-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pakaian.Clothes')),
            ],
        ),
    ]
